/**
 * Every API path in one place, so a backend route change is a one-line edit.
 * Mirrors backend/config/urls.py (all paths are relative to /api/v1).
 */

export const endpoints = {
  auth: {
    entraExchange: '/auth/entra/exchange/',
    tokenRefresh: '/auth/token/refresh/',
    me: '/auth/me/',
    logout: '/auth/logout/',
    login: '/auth/login/',
    passwordChange: '/auth/password/change/',
    passwordForgot: '/auth/password/forgot/',
  },
  employees: {
    list: '/employees/',
    detail: (id: number | string) => `/employees/${id}/`,
    me: '/employees/me/',
    myTeam: '/employees/my-team/',
    documents: (id: number | string) => `/employees/${id}/documents/`,
    photo: (id: number | string) => `/employees/${id}/photo/`,
    document: (id: number | string, documentId: number | string) =>
      `/employees/${id}/documents/${documentId}/`,
    departments: '/departments/',
    designations: '/designations/',
    orgChart: '/employees/org-chart/',
    directory: '/employees/directory/',
    directoryEntry: (id: number | string) => `/employees/directory/${id}/`,
    bankAccount: (id: number | string) => `/employees/${id}/bank-account/`,
    skills: (id: number | string) => `/employees/${id}/skills/`,
    assets: (id: number | string) => `/employees/${id}/assets/`,
    asset: (id: number | string, assetId: number | string) =>
      `/employees/${id}/assets/${assetId}/`,
    skillVocabulary: '/skills/',
    search: '/employees/search/',
    deletionRequest: (id: number | string) => `/employees/${id}/deletion-request/`,
    completeProfile: (id: number | string) => `/employees/${id}/complete-profile/`,
    profileDraft: (id: number | string) => `/employees/${id}/profile-draft/`,
    experience: (id: number | string) => `/employees/${id}/experience/`,
  },
  projects: {
    list: '/projects/',
    detail: (id: number | string) => `/projects/${id}/`,
    members: (id: number | string) => `/projects/${id}/members/`,
    allocations: (id: number | string) => `/projects/${id}/allocations/`,
    myAllocations: '/my-allocations/',
  },
  leave: {
    requests: '/leaves/',
    mine: '/leaves/me/',
    detail: (id: number | string) => `/leaves/${id}/`,
    approve: (id: number | string) => `/leaves/${id}/approve/`,
    reject: (id: number | string) => `/leaves/${id}/reject/`,
    cancel: (id: number | string) => `/leaves/${id}/cancel/`,
    pendingApprovals: '/leaves/pending-approvals/',
    hrApprovals: '/leaves/hr-approvals/',
    sendBack: (id: number | string) => `/leaves/${id}/send-back/`,
    teamCalendar: '/leaves/team-calendar/',
    balances: '/leave-balances/',
    myBalances: '/leave-balances/me/',
    types: '/leave-types/',
    holidays: '/holidays/',
  },
  timesheets: {
    list: '/timesheets/',
    mine: '/timesheets/me/',
    detail: (id: number | string) => `/timesheets/${id}/`,
    weekly: '/timesheets/weekly/',
    entries: (id: number | string) => `/timesheets/${id}/entries/`,
    submit: (id: number | string) => `/timesheets/${id}/submit/`,
    approve: (id: number | string) => `/timesheets/${id}/approve/`,
    reject: (id: number | string) => `/timesheets/${id}/reject/`,
    pendingApprovals: '/timesheets/pending-approvals/',
    currentWeekSummary: '/timesheets/current-week-summary/',
    statusByProject: '/timesheets/status/by-project/',
    statusByEmployee: '/timesheets/status/by-employee/',
    notify: '/timesheets/notify/',
  },
  payroll: {
    salaryStructures: '/salary-structures/',
    salaryStructure: (id: number | string) => `/salary-structures/${id}/`,
    runs: '/payroll-runs/',
    run: (id: number | string) => `/payroll-runs/${id}/`,
    process: (id: number | string) => `/payroll-runs/${id}/process/`,
    approve: (id: number | string) => `/payroll-runs/${id}/approve/`,
    reject: (id: number | string) => `/payroll-runs/${id}/reject/`,
    markPaid: (id: number | string) => `/payroll-runs/${id}/mark-paid/`,
    exportRun: (id: number | string) => `/payroll-runs/${id}/export/`,
    payslips: '/payslips/',
    myPayslips: '/payslips/me/',
    latestPayslip: '/payslips/latest/',
    payslipPeriods: '/payslips/periods/',
    payslipPdf: (id: number | string) => `/payslips/${id}/pdf/`,
    pushToFinance: (id: number | string) => `/payslips/${id}/process/`,
  },
  finance: {
    approvals: '/finance/approvals/',
    approval: (id: number | string) => `/finance/approvals/${id}/`,
    release: (id: number | string) => `/finance/approvals/${id}/approve/`,
    query: (id: number | string) => `/finance/approvals/${id}/query/`,
  },
  notifications: {
    list: '/notifications/',
    markRead: (id: number | string) => `/notifications/${id}/read/`,
    markAllRead: '/notifications/read-all/',
    unreadCount: '/notifications/unread-count/',
  },
  reports: {
    dashboard: '/dashboard/summary/',
    birthdays: '/dashboard/birthdays/',
    employees: '/reports/employees/',
    leave: '/reports/leave/',
    timesheet: '/reports/timesheet/',
    projects: '/reports/projects/',
  },
  administration: {
    users: '/admin/users/',
    deleteUsers: '/admin/users/delete/',
    userDetail: (id: number | string) => `/admin/users/${id}/`,
    roles: '/admin/roles/',
    permissions: '/admin/permissions/',
    settings: '/admin/settings/',
    auditLogs: '/admin/audit-logs/',
    deletionRequests: '/admin/deletion-requests/',
    approveDeletion: (id: number | string) => `/admin/deletion-requests/${id}/approve/`,
    rejectDeletion: (id: number | string) => `/admin/deletion-requests/${id}/reject/`,
  },
} as const;
