# Generated by Django 6.0.8 on 2026-08-24 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayslipApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Waiting for HR'), ('processed', 'With Finance'), ('approved', 'Released'), ('queried', 'Queried by Finance')], db_index=True, default='pending', max_length=12)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='The Finance user who released it for payment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payslips_released', to=settings.AUTH_USER_MODEL)),
                ('payslip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance_approval', to='payroll.payslip')),
                ('processed_by', models.ForeignKey(blank=True, help_text='The HR user who pushed this payslip to Finance.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payslips_processed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payslip_approvals',
                'ordering': ('-processed_at', '-created_at'),
                'indexes': [models.Index(fields=['status', '-processed_at'], name='payslip_app_status_84b5e6_idx')],
            },
        ),
    ]
