# Generated by Django 6.0.8 on 2026-08-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Set when HR/Admin issues a temporary password; forces a reset on next sign-in.'),
        ),
    ]
