# Generated by Django 6.0.8 on 2026-08-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulepermission',
            name='module',
            field=models.CharField(choices=[('authentication', 'Authentication'), ('employees', 'Employee Management'), ('projects', 'Project Management'), ('leave', 'Leave Management'), ('timesheets', 'Timesheet Management'), ('payroll', 'Payroll'), ('reports', 'Reports & Analytics'), ('administration', 'Administration')], max_length=50),
        ),
    ]
