# Generated by Django 6.0.8 on 2026-09-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_phase7_profile_and_reset"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="failed_login_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Consecutive failed sign-ins inside the lockout window. Reset on success.",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_failed_login_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="locked_until",
            field=models.DateTimeField(
                blank=True,
                help_text="Sign-in is refused until this moment. Cleared by a successful sign-in.",
                null=True,
            ),
        ),
    ]
