# Generated by Django 6.0.8 on 2026-08-24 06:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(max_length=150)),
                ('is_optional', models.BooleanField(default=False, help_text='Optional/floating holidays still count as working days.')),
            ],
            options={
                'db_table': 'holidays',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('days_per_year', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_paid', models.BooleanField(default=True)),
                ('requires_approval', models.BooleanField(default=True)),
                ('max_consecutive_days', models.PositiveSmallIntegerField(blank=True, help_text='Blank means no limit.', null=True)),
                ('allow_half_day', models.BooleanField(default=True)),
                ('carry_forward', models.BooleanField(default=False, help_text="Unused days roll into next year's allocation.")),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'leave_types',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('day_part', models.CharField(choices=[('full', 'Full day'), ('first_half', 'First half'), ('second_half', 'Second half')], default='full', max_length=12)),
                ('total_days', models.DecimalField(decimal_places=1, max_digits=5)),
                ('reason', models.TextField()),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=12)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_comment', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_decisions', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employees.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='leave_management.leavetype')),
            ],
            options={
                'db_table': 'leave_requests',
                'ordering': ('-start_date', '-applied_at'),
            },
        ),
        migrations.CreateModel(
            name='LeaveApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], max_length=12)),
                ('comment', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='leave_management.leaverequest')),
            ],
            options={
                'db_table': 'leave_approvals',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('allocated_days', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=6)),
                ('used_days', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=6)),
                ('pending_days', models.DecimalField(decimal_places=1, default=Decimal('0'), help_text='Reserved by requests awaiting a decision.', max_digits=6)),
                ('carried_forward_days', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=6)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='employees.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='leave_management.leavetype')),
            ],
            options={
                'db_table': 'leave_balances',
                'ordering': ('-year', 'leave_type__name'),
            },
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['employee', 'status'], name='leave_reque_employe_fd03a1_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['status', 'start_date'], name='leave_reque_status_cccf6b_idx'),
        ),
        migrations.AddConstraint(
            model_name='leavebalance',
            constraint=models.UniqueConstraint(fields=('employee', 'leave_type', 'year'), name='uniq_balance_per_year'),
        ),
    ]
