# Generated by Django 6.0.8 on 2026-08-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='description',
            field=models.TextField(blank=True, help_text='Shown to employees wherever the holiday appears.'),
        ),
    ]
