# Generated by Django 6.0.8 on 2026-08-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave_management", "0003_two_stage_approval_and_cc"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavetype",
            name="restricted_to_gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("female", "Female"),
                    ("male", "Male"),
                    ("other", "Other"),
                    ("undisclosed", "Prefer not to say"),
                ],
                help_text="Blank means everyone. A restricted type (maternity leave) simply does not exist for anyone else: no balance, no option to apply, no line in any total.",
                max_length=15,
            ),
        ),
    ]
