# Generated by Django 6.0.8 on 2026-08-24 16:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_profile_photo_and_blood_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_holder_name', models.CharField(help_text='Exactly as printed on the passbook.', max_length=120)),
                ('bank_name', models.CharField(max_length=120)),
                ('branch_name', models.CharField(blank=True, max_length=120)),
                ('account_number', models.CharField(help_text='Up to 34 characters, so international accounts also fit.', max_length=34, validators=[django.core.validators.MinLengthValidator(6)])),
                ('ifsc_code', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[A-Z]{4}0[A-Z0-9]{6}$', 'Enter a valid IFSC code: four letters, a zero, then six letters or digits.')])),
                ('account_type', models.CharField(choices=[('savings', 'Savings'), ('current', 'Current'), ('salary', 'Salary')], default='savings', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employee_bank_accounts',
                'ordering': ('employee__employee_code',),
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('category', models.CharField(choices=[('language', 'Programming language'), ('framework', 'Framework or library'), ('database', 'Database'), ('cloud', 'Cloud and DevOps'), ('tool', 'Tool'), ('domain', 'Domain knowledge'), ('soft', 'Professional skill'), ('other', 'Other')], default='other', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Retired skills stay on existing profiles but stop being offered.')),
            ],
            options={
                'db_table': 'skills',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['category', 'is_active'], name='skills_categor_a56138_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proficiency', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=15)),
                ('years_of_experience', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='employees.employee')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employees.skill')),
            ],
            options={
                'db_table': 'employee_skills',
                'ordering': ('skill__name',),
                'constraints': [models.UniqueConstraint(fields=('employee', 'skill'), name='uniq_employee_skill')],
            },
        ),
    ]
