# Generated by Django 6.0.8 on 2026-08-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0007_employeeasset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeedocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("id_proof", "ID proof"),
                    ("address_proof", "Address proof"),
                    ("tenth", "10th certificate"),
                    ("intermediate", "12th / intermediate certificate"),
                    ("bachelors", "Bachelor's degree"),
                    ("masters", "Master's degree"),
                    ("other_education", "Other education certificate"),
                    ("skill_certificate", "Skills certification"),
                    ("education", "Education certificate"),
                    ("experience_letter", "Experience letter"),
                    ("experience", "Experience letter (legacy)"),
                    ("contract", "Employment contract"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
