# Generated by Django 6.0.8 on 2026-08-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_employeedocument_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeasset',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('needs_repair', 'Needs repair')], default='good', help_text='State of the kit when last recorded.', max_length=20),
        ),
        migrations.AddField(
            model_name='employeeasset',
            name='issued_on',
            field=models.DateField(blank=True, help_text='When the kit was handed over.', null=True),
        ),
    ]
