# Generated by Django 6.0.8 on 2026-08-24 06:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_start_date', models.DateField(help_text='Always a Monday.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=12)),
                ('total_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('comments', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_comment', models.TextField(blank=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheet_decisions', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='employees.employee')),
            ],
            options={
                'db_table': 'timesheets',
                'ordering': ('-week_start_date',),
            },
        ),
        migrations.CreateModel(
            name='TimesheetApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('reopened', 'Reopened')], max_length=12)),
                ('comment', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='timesheets.timesheet')),
            ],
            options={
                'db_table': 'timesheet_approvals',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TimesheetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.25')), django.core.validators.MaxValueValidator(Decimal('24'))])),
                ('description', models.CharField(blank=True, max_length=500)),
                ('is_billable', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timesheet_entries', to='projects.project')),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='timesheets.timesheet')),
            ],
            options={
                'db_table': 'timesheet_entries',
                'ordering': ('work_date', 'project__code'),
            },
        ),
        migrations.AddIndex(
            model_name='timesheet',
            index=models.Index(fields=['status', 'week_start_date'], name='timesheets_status_4839b7_idx'),
        ),
        migrations.AddConstraint(
            model_name='timesheet',
            constraint=models.UniqueConstraint(fields=('employee', 'week_start_date'), name='uniq_timesheet_per_week'),
        ),
        migrations.AddIndex(
            model_name='timesheetentry',
            index=models.Index(fields=['work_date'], name='timesheet_e_work_da_d1a1fc_idx'),
        ),
        migrations.AddIndex(
            model_name='timesheetentry',
            index=models.Index(fields=['project'], name='timesheet_e_project_536c6d_idx'),
        ),
        migrations.AddConstraint(
            model_name='timesheetentry',
            constraint=models.UniqueConstraint(fields=('timesheet', 'project', 'work_date'), name='uniq_entry_per_project_day'),
        ),
    ]
